name: magv
channels:
  - defaults
dependencies:
  - ld_impl_linux-64==2.43=h712a8e2_2
  - openssl==3.4.0=hb9d3cd8_0
  - tk==8.6.13=noxft_h4845f30_101
  - ca-certificates==2024.8.30=hbcca054_0
  - libsqlite==3.47.0=hadc24fc_1
  - ncurses==6.5=he02047a_1
  - libgcc-ng==14.2.0=h69a702a_1
  - libffi==3.4.2=h7f98852_5
  - libuuid==2.38.1=h0b41bf4_0
  - libgcc==14.2.0=h77fa898_1
  - libzlib==1.3.1=hb9d3cd8_2
  - _libgcc_mutex==0.1=conda_forge
  - readline==8.2=h8228510_1
  - libnsl==2.0.1=hd590300_0
  - bzip2==1.0.8=h4bc722e_7
  - _openmp_mutex==4.5=2_gnu
  - libxcrypt==4.4.36=hd590300_1
  - tzdata==2024b=hc8b5060_0
  - pip==24.3.1=pyh8b19718_0
  - wheel==0.45.1=pyhd8ed1ab_0
  - xz==5.2.6=h166bdaf_0
  - python==3.9.20=h13acc7a_1_cpython
  - setuptools==75.6.0=pyhff2d567_1
  - libgomp==14.2.0=h77fa898_1
prefix: /home/ids/flauron-23/anaconda3/envs/magv
